### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by irvaniamirali** [MjavadH/Collection-of-404-pages#1]
Hello. I'm working on a website and came across your repository while searching for a suitable template for a 404 page.
But this code is very complicated and I am not a front end programmer
Therefore, I request you to provide me a summary of the code and only the "Matrix" page
Thanks a lot

**Comment by MjavadH** [comment]
Hello, all the pages in the repository are categorized and easy to use.
To use the "**Matrix**" page, just use the contents of the _Matrix_ folder.

The matrix page is located in this path: `4X4-Collection > Technology > Matrix` 
Download the matrix page: [Matrix.zip](https://github.com/MjavadH/4X4-Collection/files/14387636/Matrix.zip)
Copy all the files in the Matrix folder and place them on your website.

All important parts are commented in the code.

**Comment by irvaniamirali** [comment]
Thanks a lot
